service: fooder-backend
provider:
  name: aws
  runtime: nodejs10.x
  region: eu-west-2

functions:
  fooder:
    handler: handler.fooder
    environment:
      DB_HOST: ${opt:DB_HOST}
      DB_USER: ${opt:DB_USER}
      DB_PASSWORD: ${opt:DB_PASSWORD}
    events:
      - http:
          path: dietaryOptions
          method: get
          cors: true 
      - http:
          path: restaurants
          method: get
          cors: true 
      - http:
          path: restaurants/{dietaryOptionId}
          method: get
          cors: true
      - http:
          path: bookings
          method: get
          cors: true
      - http:
          path: bookings/{restaurantId}
          method: get
          cors: true
      - http:
          path: addBooking
          method: post
          cors: true
      - http:
          path: deleteBooking/{bookingId}
          method: delete
          cors: true
      - http:
          path: bookingsRestaurantsDate/{restaurantId}/{date}
          method: get
          cors: true